# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(530, 367)
        self.Button_Menu = QtWidgets.QPushButton(MainWindow)
        self.Button_Menu.setGeometry(QtCore.QRect(0, 0, 101, 28))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setBold(True)
        font.setWeight(75)
        self.Button_Menu.setFont(font)
        self.Button_Menu.setAutoExclusive(False)
        self.Button_Menu.setObjectName("Button_Menu")
        self.verticalLayoutWidget = QtWidgets.QWidget(MainWindow)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 30, 411, 251))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.InputText = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.InputText.setObjectName("InputText")
        self.verticalLayout.addWidget(self.InputText)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Telegram = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.Telegram.setObjectName("Telegram")
        self.horizontalLayout.addWidget(self.Telegram)
        self.Vkontakte = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.Vkontakte.setObjectName("Vkontakte")
        self.horizontalLayout.addWidget(self.Vkontakte)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.DeleteFilesButton = QtWidgets.QPushButton(MainWindow)
        self.DeleteFilesButton.setGeometry(QtCore.QRect(450, 290, 71, 31))
        self.DeleteFilesButton.setObjectName("DeleteFilesButton")
        self.FileButton = QtWidgets.QPushButton(MainWindow)
        self.FileButton.setGeometry(QtCore.QRect(454, 50, 71, 55))
        self.FileButton.setObjectName("FileButton")
        self.PostButton = QtWidgets.QPushButton(MainWindow)
        self.PostButton.setGeometry(QtCore.QRect(0, 327, 531, 41))
        self.PostButton.setObjectName("PostButton")
        self.FileNames = QtWidgets.QLabel(MainWindow)
        self.FileNames.setGeometry(QtCore.QRect(30, 295, 411, 21))
        self.FileNames.setObjectName("FileNames")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Dialog"))
        self.Button_Menu.setText(_translate("MainWindow", "Платформы"))
        self.Telegram.setText(_translate("MainWindow", "ТЕЛЕГРАМ"))
        self.Vkontakte.setText(_translate("MainWindow", "ВКОНТАКТЕ"))
        self.DeleteFilesButton.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>ОЧИСТИТЬ ФАЙЛЫ</p></body></html>"))
        self.DeleteFilesButton.setText(_translate("MainWindow", "ОЧИСТИТЬ"))
        self.FileButton.setText(_translate("MainWindow", "ФАЙЛЫ"))
        self.PostButton.setText(_translate("MainWindow", "РАЗМЕСТИТЬ"))
        self.FileNames.setText(_translate("MainWindow", "ВЫБРАННЫЕ ФАЙЛЫ:"))